version : "3.9"

services:
    prometheus:
        image: prom/prometheus:latest
        restart: always
        ports:
          - 9090:9090

    grafana:
        image: grafana/grafana:latest
        restart: always
        ports:
          - 3000:3000

