version: '3.2'
services:
  mongo:
    restart: 'always'
    ports:
    - '27017:27017'
    image: mongo
    container_name: mongo-container
    networks:
      net:
        aliases:
        - 'mongodb-service'
  mongo_exporter:
    restart: 'always'
    ports:
    - '9001:9001'
    image: gpuliyar/mongo-exporter
    container_name: mongo-exporter-container
    environment:
    - 'MONGO_SERVICE=mongodb-service'
    - 'MONGO_PORT=27017'
    depends_on:
    - mongo
    networks:
      net:
        aliases:
        - 'mongodb-exporter-service'
  grafana:
    restart: 'always'
    ports:
    - '3000:3000'
    image: grafana/grafana
    container_name: grafana-container
  prometheus:
    restart: 'always'
    ports:
    - '9090:9090'
    image: prom/prometheus
    container_name: prometheus-container
    command:
    - '--config.file=/prometheus/config/prometheus.yaml'
      #    - '--storage.tsdb.path=/data'
    volumes:
    - ./config:/prometheus/config
    - ./data:/data
    depends_on:
    - mongo_exporter
    networks:
      net:
        aliases:
        - 'prometheus-service'
networks:
  net:
